---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: prod
data:
  GCP_PROJECT_ID: "hmm-dev"
  POSTGRES_DATABASE: "todo-app-prod"
  POSTGRES_USERNAME: "postgres"
  GCP_IDP_TENANT_ID: "todo-prod-ok9y1"