---
apiVersion: v1
kind: Namespace
metadata:
  name: todo-staging
  labels:
    name: todo-staging

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: todo-staging
data:
  GCP_PROJECT_ID: "hmm-dev"
  POSTGRES_DATABASE: "todo_staging"
  POSTGRES_USERNAME: "todo_staging_user"
  GCP_IDP_TENANT_ID: "todo-staging-g7vip"
  POSTGRES_HOST: "172.29.64.5"

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: todo-app-ingress
  namespace: todo-staging
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  tls:
    - hosts:
        - "todo.staging.hmm.dev"
      secretName: todo-app-cert-secret
  rules:
    - host: "todo.staging.hmm.dev"
      http:
        paths:
          - path: /
            backend:
              serviceName: todo-app-service
              servicePort: 8080
