projects:
  todo:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        graphQLApiId: 3y6zuvifqnhpjmlvgcioynj6vm
      endpoints:
        prod: >-
          https://co4cgc5vazdmlnl5nqdrxnpubm.appsync-api.us-east-1.amazonaws.com/graphql
