---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: todo-app-ingress
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  tls:
    - hosts:
        - "todo.staging.hmm.dev"
      secretName: todo-app-cert-secret
  rules:
    - host: "todo.staging.hmm.dev"
      http:
        paths:
          - path: /
            backend:
              serviceName: todo-app-service
              servicePort: 8080
