---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          # The parameter below is replaced during circle build
          image: gcr.io/hmm-dev/todo-app:${parameters.tag}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.5"
            requests:
              memory: "256Mi"
              cpu: "0.1"
          envFrom:
            - configMapRef:
                name: todo-app-config
            - secretRef:
                name: todo-app-secrets

          readinessProbe:
            httpGet:
              path: /_health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 15

          livenessProbe:
            httpGet:
              path: /_health/alive
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5

          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/config/GCP_SERVICE_ACCOUNT_KEY"
          volumeMounts:
            - name: gcp-key
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: gcp-key
          secret:
            secretName: todo-app-secrets
